### ISSUE TITLE
Error getting bulbs

### ISSUE THREAD

**Issue by wint100** [mthyden/PhillipsHueSIMPLSharp#10]
Hi,

I've loaded in the 2.2 demo using Studio 1.71 but when running and debugging in ToolBox, I get the following error. the API key fetch was successful but it fails getting the bulbs:

Error getting bulbs: System.ArgumentNullException: Value can not be null.    00:01:49.891
Parameter name: value    00:01:49.891
   at Newtonsoft.Json.Linq.JToken.m(JToken A_0)    00:01:49.891
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)    00:01:49.891
   at HueLights.HueProc.ProcBulbs(String jsondata)    00:01:49.891
   at HueLights.HueProc.OnInfoReceived(Object source, InfoEventArgs e)    00:01:49.891
   at HueLights.HueBridge.OnInfoReceived(String infotype, String jsondata)    00:01:49.891
   at HueLights.HueBridge.GetBridgeInfo(String infotype)    00:01:49.891
   at HueLights.HueProc.getData()    00:01:49.891
   at UserModule_HUELIGHTSPROC_R1_5.UserModuleClass_HUELIGHTSPROC_R1_5.GETBULBDATA_OnPush_2(Object __EventInfo__)    00:01:49.891
   at Amib.Threading.Internal.WorkItem.o()    00:01:49.891
   at Amib.Threading.Internal.WorkItem.Execute()    00:01:49.891
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)    00:01:49.891
   at Amib.Threading.SmartThreadPool.p()    00:01:49.891

**Comment by mthyden** [comment]
Any chance you can provide me the Bulb/Group/Scene data from the bridge, instructions can be found at the Hue API site below., Just throw the results for each request into a text file so I can take a closer look at your bridge data.

https://developers.meethue.com/documentation/getting-started <https://developers.meethue.com/documentation/getting-started>

I know some folks are still seeing a runtime error on the initial request from time to time, but I believe it still gets all their bridge data correctly. 

On Feb 26, 2018, at 2:22 PM, wint100 <notifications@github.com> wrote:

Hi,

I've loaded in the 2.2 demo using Studio 1.71 but when running and debugging in ToolBox, I get the following error. the API key fetch was successful but it fails getting the bulbs:

Parameter name: value 00:01:49.891
at Newtonsoft.Json.Linq.JToken.m(JToken A_0) 00:01:49.891
at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value) 00:01:49.891
at HueLights.HueProc.ProcBulbs(String jsondata) 00:01:49.891
at HueLights.HueProc.OnInfoReceived(Object source, InfoEventArgs e) 00:01:49.891
at HueLights.HueBridge.OnInfoReceived(String infotype, String jsondata) 00:01:49.891
at HueLights.HueBridge.GetBridgeInfo(String infotype) 00:01:49.891
at HueLights.HueProc.getData() 00:01:49.891
at UserModule_HUELIGHTSPROC_R1_5.UserModuleClass_HUELIGHTSPROC_R1_5.GETBULBDATA_OnPush_2(Object EventInfo) 00:01:49.891
at Amib.Threading.Internal.WorkItem.o() 00:01:49.891
at Amib.Threading.Internal.WorkItem.Execute() 00:01:49.891
at Amib.Threading.SmartThreadPool.e(WorkItem A_0) 00:01:49.891
at Amib.Threading.SmartThreadPool.p() 00:01:49.891

**Comment by wint100** [comment]
Yes will do. Strangely it works fine when using SIMPL windows to upload the demo.

Regards,

Mark Wint
BEC Ltd

On 26 Feb 2018, at 23:26, Monte Thyden <notifications@github.com<mailto:notifications@github.com>> wrote:

Any chance you can provide me the Bulb/Group/Scene data from the bridge, instructions can be found at the Hue API site below., Just throw the results for each request into a text file so I can take a closer look at your bridge data.

https://developers.meethue.com/documentation/getting-started <https://developers.meethue.com/documentation/getting-started>

I know some folks are still seeing a runtime error on the initial request from time to time, but I believe it still gets all their bridge data correctly.

On Feb 26, 2018, at 2:22 PM, wint100 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

I've loaded in the 2.2 demo using Studio 1.71 but when running and debugging in ToolBox, I get the following error. the API key fetch was successful but it fails getting the bulbs:

Parameter name: value 00:01:49.891
at Newtonsoft.Json.Linq.JToken.m(JToken A_0) 00:01:49.891
at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value) 00:01:49.891
at HueLights.HueProc.ProcBulbs(String jsondata) 00:01:49.891
at HueLights.HueProc.OnInfoReceived(Object source, InfoEventArgs e) 00:01:49.891
at HueLights.HueBridge.OnInfoReceived(String infotype, String jsondata) 00:01:49.891
at HueLights.HueBridge.GetBridgeInfo(String infotype) 00:01:49.891
at HueLights.HueProc.getData() 00:01:49.891
at UserModule_HUELIGHTSPROC_R1_5.UserModuleClass_HUELIGHTSPROC_R1_5.GETBULBDATA_OnPush_2(Object EventInfo) 00:01:49.891
at Amib.Threading.Internal.WorkItem.o() 00:01:49.891
at Amib.Threading.Internal.WorkItem.Execute() 00:01:49.891
at Amib.Threading.SmartThreadPool.e(WorkItem A_0) 00:01:49.891
at Amib.Threading.SmartThreadPool.p() 00:01:49.891

**Comment by mthyden** [comment]
ah weird, yeah if your bridge data works with the SIMPL program then chances are its not the data that is causing the issue. I had in a previous version of the modules created Studio devices with them to expose macro programming but found that the upgrade path for module changes was less forgiving so I didn’t keep up on them. So your using the same initialization methods in both CS and SIMPL I take it? did you import the modules into Studio but then create or update an system with Macro/hybrid support? It’s possible Studio autologic generation could be interfering somehow but would be hard to tell. 



On Feb 26, 2018, at 10:54 PM, wint100 <notifications@github.com> wrote:

Yes will do. Strangely it works fine when using SIMPL windows to upload the demo. 

Regards, 

Mark Wint 
BEC Ltd 

On 26 Feb 2018, at 23:26, Monte Thyden <notifications@github.com<mailto:notifications@github.com>> wrote: 

Any chance you can provide me the Bulb/Group/Scene data from the bridge, instructions can be found at the Hue API site below., Just throw the results for each request into a text file so I can take a closer look at your bridge data. 

https://developers.meethue.com/documentation/getting-started <https://developers.meethue.com/documentation/getting-started> 

I know some folks are still seeing a runtime error on the initial request from time to time, but I believe it still gets all their bridge data correctly. 

On Feb 26, 2018, at 2:22 PM, wint100 <notifications@github.com<mailto:notifications@github.com>> wrote: 

Hi, 

I've loaded in the 2.2 demo using Studio 1.71 but when running and debugging in ToolBox, I get the following error. the API key fetch was successful but it fails getting the bulbs: 

Parameter name: value 00:01:49.891 
at Newtonsoft.Json.Linq.JToken.m(JToken A_0) 00:01:49.891 
at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value) 00:01:49.891 
at HueLights.HueProc.ProcBulbs(String jsondata) 00:01:49.891 
at HueLights.HueProc.OnInfoReceived(Object source, InfoEventArgs e) 00:01:49.891 
at HueLights.HueBridge.OnInfoReceived(String infotype, String jsondata) 00:01:49.891 
at HueLights.HueBridge.GetBridgeInfo(String infotype) 00:01:49.891 
at HueLights.HueProc.getData() 00:01:49.891 
at UserModule_HUELIGHTSPROC_R1_5.UserModuleClass_HUELIGHTSPROC_R1_5.GETBULBDATA_OnPush_2(Object EventInfo) 00:01:49.891 
at Amib.Threading.Internal.WorkItem.o() 00:01:49.891 
at Amib.Threading.Internal.WorkItem.Execute() 00:01:49.891 
at Amib.Threading.SmartThreadPool.e(WorkItem A_0) 00:01:49.891 
at Amib.Threading.SmartThreadPool.p() 00:01:49.891

**Comment by wint100** [comment]
I saw this issue again with SIMPL Windows. It seems to be when trying to get bulbs. Triggering the Refresh on the Bulbs module gives an error as shown previously and the bulbs_list is always empty. The Rooms are returned just fine, as is the bulb count (it discovers 5 in my system), but getting bulb1_name fails.

________________________________

**Comment by wint100** [comment]
It looks like ‘hue_busy_alt’ goes high as soon as the program is started, which triggers the ‘get_rms’ stepper (and get bulbs in my modified program). This fails because the bridge isn’t online yet. hue_busy_alt should only trigger when the oneshot ‘wait till after proc busy before getting rooms’ triggers but this happens on program start and when the one shot triggers.

**Comment by mthyden** [comment]
I’ve attached a screenshot of my home setup but not sure if github will accept it.

essentially I have a 10sec delay off of program start which triggers the Processor module hue_init signal. I then take the hue_online signal to trigger a stepper to init the various room modules, The last couple revs I haven’t done regression testing off the actual demo program, just my house program and have recompiled the demo program with the tested updated modules. Its cumbersome to load the test program at home because of the API key and multiple slots etc.

So your saying your not seeing the processor module come online at all? It doesn’t complete all its routines or that is coming online and your individual room/bulb modules are not coming online?

 

On Feb 28, 2018, at 12:44 PM, wint100 <notifications@github.com> wrote:

It looks like ‘hue_busy_alt’ goes high as soon as the program is started, which triggers the ‘get_rms’ stepper (and get bulbs in my modified program). This fails because the bridge isn’t online yet. hue_busy_alt should only trigger when the oneshot ‘wait till after proc busy before getting rooms’ triggers but this happens on program start and when the one shot triggers.

**Comment by wint100** [comment]
Looks like the sreenshot has bene removed.

The processor does initialise and all rooms are returned, room number, bulb number etc.. I just get an error when the bulb1_get signal is triggered to get the bulb1 info.

I’ve done the same as you, I’ve changed the stepper to trigger from the hue_online signal rather than the original hue_busy_alt signal that came from the oneshot in 2.2. I still can’t get the bulb to return. The bulblist seems to populate, but every time bulb1_get is triggered an error is thrown ‘Error getting bulb data:’

So, get and working with rooms is fine, it’s just the bulb response that gives an error.

**Comment by mthyden** [comment]
ah ok, so processor is getting all the data correctly, just an individual bulb module isn’t coming online.

Have you tried manually putting in the light name in the parameter field rather then feeding the name from an intersystem symbol? do you have the same problem with Room modules? or is it just the bulb? I typically just use room modules at home so I’ll drop a bulb or two tonight and test it.

On Feb 28, 2018, at 1:14 PM, wint100 <notifications@github.com> wrote:

Looks like the sreenshot has bene removed. 

The processor does initialise and all rooms are returned, room number, bulb number etc.. I just get an error when the bulb1_get signal is triggered to get the bulb1 info. 

I’ve done the same as you, I’ve changed the stepper to trigger from the hue_online signal rather than the original hue_busy_alt signal that came from the oneshot in 2.2. I still can’t get the bulb to return. The bulblist seems to populate, but every time bulb1_get is triggered an error is thrown ‘Error getting bulb data:’ 

So, get and working with rooms is fine, it’s just the bulb response that gives an error.

**Comment by wint100** [comment]
Yes just bulbs, rooms work great. It is the intersystem that seems to be the problem. The bulb_list is fed in and looks correct, but the bulb name outputs are always empty strings.

**Comment by mthyden** [comment]
so you see values in the rx$ of the intersystem? make sure the option is set to 1d no offset and throw the output signals and the input signal into a Make String permanent

On Feb 28, 2018, at 1:42 PM, wint100 <notifications@github.com> wrote:

Yes just bulbs, rooms work great. It is the intersystem that seems to be the problem. The bulb_list is fed in and looks correct, but the bulb name outputs are always empty strings.

**Comment by wint100** [comment]
Yes I see a value for the bulb_list which goes into the intersystem rx$, but all outputs are empty strings from the intersystem. I can see these empty string when debugging. Option is 1, offset is 0.

hue_bulb_list  \xC8\x00\xFF  00:01:00.032
bulb1_name  <empty>  00:01:00.032

**Comment by mthyden** [comment]
put the bulb names into a make string permanent, the serials are most likely dissapearing

On Feb 28, 2018, at 1:52 PM, wint100 <notifications@github.com> wrote:

Yes I see a value for the bulb_list which goes into the intersystem rx$, but all outputs are empty strings from the intersystem. I can see these empty string when debugging. Option is 1, offset is 0. 

hue_bulb_list \xC8\x00\xFF 00:01:00.032 
bulb1_name <empty> 00:01:00.032

**Comment by wint100** [comment]
That seems to give another error now every time get bulb is called in the HueBulb module:
Exception is System.NullReferenceException: NullReferenceException    00:00:13.109
   at HueLights.HttpConnect.Request(String url, String cmd, RequestType reqtype)    00:00:13.109
   at HueLights.HueLight.GetBulb()    00:00:13.109
   at UserModule_HUEBULB_R2_1.UserModuleClass_HUEBULB_R2_1.GETINFO_OnPush_0(Object __EventInfo__)    00:00:13.109
   at Amib.Threading.Internal.WorkItem.o()    00:00:13.109
   at Amib.Threading.Internal.WorkItem.Execute()    00:00:13.109
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)    00:00:13.109
   at Amib.Threading.SmartThreadPool.p()    00:00:13.109

**Comment by mthyden** [comment]
can you hardcode the bulb name in the parameter field and remove the serial join? it still looks like the module doesn’t see the bulb name

On Feb 28, 2018, at 2:03 PM, wint100 <notifications@github.com> wrote:

That seems to give another error now every time get bulb is called in the HueBulb module: 
Exception is System.NullReferenceException: NullReferenceException 00:00:13.109 
at HueLights.HttpConnect.Request(String url, String cmd, RequestType reqtype) 00:00:13.109 
at HueLights.HueLight.GetBulb() 00:00:13.109 
at UserModule_HUEBULB_R2_1.UserModuleClass_HUEBULB_R2_1.GETINFO_OnPush_0(Object __EventInfo__) 00:00:13.109 
at Amib.Threading.Internal.WorkItem.o() 00:00:13.109 
at Amib.Threading.Internal.WorkItem.Execute() 00:00:13.109 
at Amib.Threading.SmartThreadPool.e(WorkItem A_0) 00:00:13.109 
at Amib.Threading.SmartThreadPool.p() 00:00:13.109

**Comment by wint100** [comment]
I’ll try that thanks. It seems like the ProcBulbs method in the c# class isn’t g etting the bulb names. The code looks correct providing the hue bridge returns the bulb name exactly as “name” as the method is adding this to the HueBulb before adding to the collection.

string name = (string)json[id]["name"];

**Comment by mthyden** [comment]
I thought you had already confirmed you were getting a bulb count and the there was data in the intersystem? ok back to square one then. I’ll need the bulb bridge data the raw JSON in order to troubleshoot and see if something is causing an issue in there. in my previous update there was a fix for Ikea bulbs which I hadn’t accounted for but that should be resolved. I have a small test program that reads the JSON data as a text file and processes it using the same routine and reports failures, etc

On Feb 28, 2018, at 2:32 PM, wint100 <notifications@github.com> wrote:

I’ll try that thanks. It seems like the ProcBulbs method in the c# class isn’t g etting the bulb names. The code looks correct providing the hue bridge returns the bulb name exactly as “name” as the method is adding this to the HueBulb before adding to the collection. 

string name = (string)json[id]["name"];

**Comment by wint100** [comment]
Yes I’m getting a bulb count of 5 and I thought the bulb-list from the processor was OK but when comparing to the room_list it seems too short of a string.

Any tips on getting the raw JSON? I can use a browser and fiddler.
MPLSha

**Comment by wint100** [comment]
Raw json attached

**Comment by wint100** [comment]
Interestingly, the ID of the bulbs are 6-10, whereas I’m looking for 1-5, maybe I just need to expand the HueBulb to read bulb names 6-10. Not sure why 1-5 would be empty in the bridge though, maybe Philips reserve bulbs 1-5 for something else.

"lights": {
                              "6": {
                                             "state": {
                                                            "on": true,
                                                            "bri": 127,
                                                            "hue": 12828,
                                                            "sat": 52,
                                                            "effect": "none",
                                                            "xy": [
                                                                           0.4578,
                                                                           0.412
                                                            ],
                                                            "alert": "none",
                                                            "colormode": "xy",
                                                            "mode": "homeautomation",
                                                            "reachable": true
                                             },
                                             "swupdate": {
                                                            "state": "noupdates",
                                                            "lastinstall": "2017-12-08T19:38:16"
                                             },
                                             "type": "Color light",
                                             "name": "Iris Lamp",
                                             "modelid": "LLC010",
                                             "manufacturername": "Philips",
                                             "capabilities": {
                                                            "certified": true,
                                                            "streaming": {
                                                                           "renderer": true,
                                                                           "proxy": false
                                                            }
                                             },
                                             "uniqueid": "00:17:88:01:00:c2:24:78-0b",
                                             "swversion": "5.105.1.21778"
                              },
                              "7": {
                                             "state": {
                                                            "on": false,
                                                            "bri": 0,
                                                            "alert": "none",
                                                            "mode": "homeautomation",
                                                            "reachable": false
                                             },
                                             "swupdate": {
                                                            "state": "noupdates",
                                                            "lastinstall": null
                                             },
                                             "type": "Dimmable light",
                                             "name": "Living Room Large Lamp",
                                             "modelid": "LWB010",
                                             "manufacturername": "Philips",
                                             "capabilities": {
                                                            "certified": true,
                                                            "streaming": {
                                                                           "renderer": false,
                                                                           "proxy": false
                                                            }
                                             },
                                             "uniqueid": "00:17:88:01:02:6e:c6:84-0b",
                                             "swversion": "1.29.0_r21169",
                                             "swconfigid": "C40F3F07",
                                             "productid": "Philips-LWB010-1-A19DLv3"
                              },
                              "8": {
                                             "state": {
                                                            "on": true,
                                                            "bri": 254,
                                                            "alert": "none",
                                                            "mode": "homeautomation",
                                                            "reachable": true
                                             },
                                             "swupdate": {
                                                            "state": "noupdates",
                                                            "lastinstall": null
                                             },
                                             "type": "Dimmable light",
                                             "name": "Living Room Small Lamp",
                                             "modelid": "LWB010",
                                             "manufacturername": "Philips",
                                             "capabilities": {
                                                            "certified": true,
                                                            "streaming": {
                                                                           "renderer": false,
                                                                           "proxy": false
                                                            }
                                             },
                                             "uniqueid": "00:17:88:01:02:6e:e2:bb-0b",
                                             "swversion": "1.29.0_r21169",
                                             "swconfigid": "C40F3F07",
                                             "productid": "Philips-LWB010-1-A19DLv3"
                              },
                              "9": {
                                             "state": {
                                                            "on": true,
                                                            "bri": 254,
                                                            "ct": 366,
                                                            "alert": "none",
                                                            "colormode": "ct",
                                                            "mode": "homeautomation",
                                                            "reachable": true
                                             },
                                             "swupdate": {
                                                            "state": "noupdates",
                                                            "lastinstall": null
                                             },
                                             "type": "Color temperature light",
                                             "name": "Front Room Large Lamp",
                                             "modelid": "LTW001",
                                             "manufacturername": "Philips",
                                             "capabilities": {
                                                            "certified": true,
                                                            "streaming": {
                                                                           "renderer": false,
                                                                           "proxy": false
                                                            }
                                             },
                                             "uniqueid": "00:17:88:01:02:7c:20:80-0b",
                                             "swversion": "5.105.0.21536"
                              },
                              "10": {
                                             "state": {
                                                            "on": false,
                                                            "bri": 254,
                                                            "alert": "none",
                                                            "mode": "homeautomation",
                                                            "reachable": false
                                             },
                                             "swupdate": {
                                                            "state": "noupdates",
                                                            "lastinstall": "2018-02-27T06:55:29"
                                             },
                                             "type": "Dimmable light",
                                             "name": "Back Outside Wall",
                                             "modelid": "LWB010",
                                             "manufacturername": "Philips",
                                             "capabilities": {
                                                            "certified": true,
                                                            "streaming": {
                                                                           "renderer": false,
                                                                           "proxy": false
                                                            }
                                             },
                                             "uniqueid": "00:17:88:01:03:0a:39:57-0b",
                                             "swversion": "1.29.0_r21169",
                                             "swconfigid": "FF6681C4",
                                             "productid": "Philips-LWB010-1-A19DLv4"
                              }
               },

**Comment by mthyden** [comment]
I don’t line up the actual bulb ID with my list, my list gets its own key for which bulb it finds in the order its read. I’ll run this through my test program and see what its bombing on, at first glance it looks ok.

On Feb 28, 2018, at 2:54 PM, wint100 <notifications@github.com> wrote:

Interestingly, the ID of the bulbs are 6-10, whereas I’m looking for 1-5, maybe I just need to expand the HueBulb to read bulb names 6-10. Not sure why 1-5 would be empty in the bridge though, maybe Philips reserve bulbs 1-5 for something else. 

"lights": { 
"6": { 
"state": { 
"on": true, 
"bri": 127, 
"hue": 12828, 
"sat": 52, 
"effect": "none", 
"xy": [ 
0.4578, 
0.412 
], 
"alert": "none", 
"colormode": "xy", 
"mode": "homeautomation", 
"reachable": true 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": "2017-12-08T19:38:16" 
}, 
"type": "Color light", 
"name": "Iris Lamp", 
"modelid": "LLC010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": true, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:00:c2:24:78-0b", 
"swversion": "5.105.1.21778" 
}, 
"7": { 
"state": { 
"on": false, 
"bri": 0, 
"alert": "none", 
"mode": "homeautomation", 
"reachable": false 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": null 
}, 
"type": "Dimmable light", 
"name": "Living Room Large Lamp", 
"modelid": "LWB010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:02:6e:c6:84-0b", 
"swversion": "1.29.0_r21169", 
"swconfigid": "C40F3F07", 
"productid": "Philips-LWB010-1-A19DLv3" 
}, 
"8": { 
"state": { 
"on": true, 
"bri": 254, 
"alert": "none", 
"mode": "homeautomation", 
"reachable": true 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": null 
}, 
"type": "Dimmable light", 
"name": "Living Room Small Lamp", 
"modelid": "LWB010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:02:6e:e2:bb-0b", 
"swversion": "1.29.0_r21169", 
"swconfigid": "C40F3F07", 
"productid": "Philips-LWB010-1-A19DLv3" 
}, 
"9": { 
"state": { 
"on": true, 
"bri": 254, 
"ct": 366, 
"alert": "none", 
"colormode": "ct", 
"mode": "homeautomation", 
"reachable": true 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": null 
}, 
"type": "Color temperature light", 
"name": "Front Room Large Lamp", 
"modelid": "LTW001", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:02:7c:20:80-0b", 
"swversion": "5.105.0.21536" 
}, 
"10": { 
"state": { 
"on": false, 
"bri": 254, 
"alert": "none", 
"mode": "homeautomation", 
"reachable": false 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": "2018-02-27T06:55:29" 
}, 
"type": "Dimmable light", 
"name": "Back Outside Wall", 
"modelid": "LWB010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:03:0a:39:57-0b", 
"swversion": "1.29.0_r21169", 
"swconfigid": "FF6681C4", 
"productid": "Philips-LWB010-1-A19DLv4" 
} 
}, 

From: Mark Wint <mark.wint@outlook.com> 
Sent: 28 February 2018 21:50 
To: Mark Wint <mark@mwint.co.uk>; mthyden/PhillipsHueSIMPLSharp <reply@reply.github.com> 
Cc: mthyden/PhillipsHueSIMPLSharp <PhillipsHueSIMPLSharp@noreply.github.com>; Author <author@noreply.github.com> 
Subject: RE: [mthyden/PhillipsHueSIMPLSharp] Error getting bulbs (#10) 

Raw json attached

**Comment by wint100** [comment]
Full JSON in case you didn't get the txt file:

[Raw.txt](https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1769045/Raw.txt)

**Comment by mthyden** [comment]
I just read your other email, the fact your getting a bulb count makes me think its parsing it all correctly, that comes directly from the simplsharp list count property, pretty weird that the itnersystem isn’t getting the bulb list, I’ll have to chew on this a little, I may not be able to dig too deep till the weekend but will see what I can do tonight

On Feb 28, 2018, at 3:06 PM, Monte Thyden <mthyden@mac.com> wrote:

I don’t line up the actual bulb ID with my list, my list gets its own key for which bulb it finds in the order its read. I’ll run this through my test program and see what its bombing on, at first glance it looks ok.

On Feb 28, 2018, at 2:54 PM, wint100 <notifications@github.com <mailto:notifications@github.com>> wrote:

Interestingly, the ID of the bulbs are 6-10, whereas I’m looking for 1-5, maybe I just need to expand the HueBulb to read bulb names 6-10. Not sure why 1-5 would be empty in the bridge though, maybe Philips reserve bulbs 1-5 for something else. 

"lights": { 
"6": { 
"state": { 
"on": true, 
"bri": 127, 
"hue": 12828, 
"sat": 52, 
"effect": "none", 
"xy": [ 
0.4578, 
0.412 
], 
"alert": "none", 
"colormode": "xy", 
"mode": "homeautomation", 
"reachable": true 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": "2017-12-08T19:38:16" 
}, 
"type": "Color light", 
"name": "Iris Lamp", 
"modelid": "LLC010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": true, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:00:c2:24:78-0b", 
"swversion": "5.105.1.21778" 
}, 
"7": { 
"state": { 
"on": false, 
"bri": 0, 
"alert": "none", 
"mode": "homeautomation", 
"reachable": false 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": null 
}, 
"type": "Dimmable light", 
"name": "Living Room Large Lamp", 
"modelid": "LWB010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:02:6e:c6:84-0b", 
"swversion": "1.29.0_r21169", 
"swconfigid": "C40F3F07", 
"productid": "Philips-LWB010-1-A19DLv3" 
}, 
"8": { 
"state": { 
"on": true, 
"bri": 254, 
"alert": "none", 
"mode": "homeautomation", 
"reachable": true 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": null 
}, 
"type": "Dimmable light", 
"name": "Living Room Small Lamp", 
"modelid": "LWB010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:02:6e:e2:bb-0b", 
"swversion": "1.29.0_r21169", 
"swconfigid": "C40F3F07", 
"productid": "Philips-LWB010-1-A19DLv3" 
}, 
"9": { 
"state": { 
"on": true, 
"bri": 254, 
"ct": 366, 
"alert": "none", 
"colormode": "ct", 
"mode": "homeautomation", 
"reachable": true 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": null 
}, 
"type": "Color temperature light", 
"name": "Front Room Large Lamp", 
"modelid": "LTW001", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:02:7c:20:80-0b", 
"swversion": "5.105.0.21536" 
}, 
"10": { 
"state": { 
"on": false, 
"bri": 254, 
"alert": "none", 
"mode": "homeautomation", 
"reachable": false 
}, 
"swupdate": { 
"state": "noupdates", 
"lastinstall": "2018-02-27T06:55:29" 
}, 
"type": "Dimmable light", 
"name": "Back Outside Wall", 
"modelid": "LWB010", 
"manufacturername": "Philips", 
"capabilities": { 
"certified": true, 
"streaming": { 
"renderer": false, 
"proxy": false 
} 
}, 
"uniqueid": "00:17:88:01:03:0a:39:57-0b", 
"swversion": "1.29.0_r21169", 
"swconfigid": "FF6681C4", 
"productid": "Philips-LWB010-1-A19DLv4" 
} 
}, 

From: Mark Wint <mark.wint@outlook.com <mailto:mark.wint@outlook.com>> 
Sent: 28 February 2018 21:50 
To: Mark Wint <mark@mwint.co.uk <mailto:mark@mwint.co.uk>>; mthyden/PhillipsHueSIMPLSharp <reply@reply.github.com <mailto:reply@reply.github.com>> 
Cc: mthyden/PhillipsHueSIMPLSharp <PhillipsHueSIMPLSharp@noreply.github.com <mailto:PhillipsHueSIMPLSharp@noreply.github.com>>; Author <author@noreply.github.com <mailto:author@noreply.github.com>> 
Subject: RE: [mthyden/PhillipsHueSIMPLSharp] Error getting bulbs (#10) 

Raw json attached

**Comment by mthyden** [comment]
great, for giggles can you send me the rooms and scenes

On Feb 28, 2018, at 3:09 PM, wint100 <notifications@github.com> wrote:

Full JSON in case you didn't get the txt file:

Raw.txt <https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1769045/Raw.txt>

**Comment by mthyden** [comment]
oh nvm its included, all good

On Feb 28, 2018, at 3:09 PM, wint100 <notifications@github.com> wrote:

Full JSON in case you didn't get the txt file:

Raw.txt <https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1769045/Raw.txt>

**Comment by mthyden** [comment]
you may be on to something regarding bulb list. The bulb processing logic I wrote years ago and I have a new branch where I’ve redone most of it but its not ready for primetime yet so still updating this current branch. I checked my bulb data and it starts at 1, I need to review how I reconcile the IDs with my list keys. A simple test would be to define the remaining sigs off the intersystem up to like 12 and in debug see what values populate after 5. If that is what is happening that was not my intent for the bridge bulb ID to define its position, I’ll need to fix that.

On Feb 28, 2018, at 3:12 PM, Monte Thyden <mthyden@mac.com> wrote:

oh nvm its included, all good

On Feb 28, 2018, at 3:09 PM, wint100 <notifications@github.com <mailto:notifications@github.com>> wrote:

Full JSON in case you didn't get the txt file:

Raw.txt <https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1769045/Raw.txt>

**Comment by mthyden** [comment]
yep you are totally right, my bulb data skips bulb ID 10 and goes on to 11 and 12. in the intersystem list 10 is empty. Totally not what I had intended and I’m a little embarrassed but least we know, yeah I’ll resolve this for now just find it on the intersystem list and pipe it to your desired modules. 

On Feb 28, 2018, at 3:55 PM, Monte Thyden <mthyden@mac.com> wrote:

you may be on to something regarding bulb list. The bulb processing logic I wrote years ago and I have a new branch where I’ve redone most of it but its not ready for primetime yet so still updating this current branch. I checked my bulb data and it starts at 1, I need to review how I reconcile the IDs with my list keys. A simple test would be to define the remaining sigs off the intersystem up to like 12 and in debug see what values populate after 5. If that is what is happening that was not my intent for the bridge bulb ID to define its position, I’ll need to fix that.

On Feb 28, 2018, at 3:12 PM, Monte Thyden <mthyden@mac.com <mailto:mthyden@mac.com>> wrote:

oh nvm its included, all good

On Feb 28, 2018, at 3:09 PM, wint100 <notifications@github.com <mailto:notifications@github.com>> wrote:

Full JSON in case you didn't get the txt file:

Raw.txt <https://github.com/mthyden/PhillipsHueSIMPLSharp/files/1769045/Raw.txt>

**Comment by wint100** [comment]
That's great that you've found the issue. I can now get bulb 6.

When you do updates (2,1-2.2 etc..) do you simply update the simpl# modules and release the new SIMPL+ modules? I'm very new to Crestron programming. I've done plenty of C#, which is what drew me to this project, but have done nothing in SIMPL so I'm trying to understand common practices. I take it the demo SIMPL program you provide stays the same between releases but the modules get updated. So when you release 2.3, I can simply replace the old modules and not have to change anything in my SIMPL program.

I've still got to explore SIMPL# Pro as well, I really like how C# is used and that BACnet classes are now available in SIMPL# 2.0. I couldn't see them in SIMPL# 1.x.

**Comment by wint100** [comment]
Although I now get the bulb6_name, calling the init or get function of the Bulb module returns nothing. Get usually returns an error. Init on the Room gets the rooms scenes etc.. but init on the HueBulb module doesn't seem to do anything. I use the make string permanent on the Bulb6_name.

**Comment by mthyden** [comment]
hmm yeah I tested it last night which is where I noticed my bulb id10 was missing. for my test I only defined bulbs 1-4, perhaps the skipping so for you past 5 other issues are exposed given the list mis-alignment, I’ll have to dig in and get the to the original root cause. I’ll try defining all my remaining bulbs first and see if I see the same as what you are seeing.

To your other questions regarding the SIMPL/SIMPLSharp environment, it all depends on what needs to change which dictates what changes regarding the various interfaces. the simplsharp library compiles into a CLZ which is a wrapper for the underlying dll. Simpl+ is our older language extension platform for SIMPL which we now use as our gatekeeper to bring in simplsharp libraries, the SIMPL WIndows has UMCs which are just wrapped logic symbols and other embedded modules which can include other SIMPL modules or simpl+ stuff. I suspect but could be wrong that whatever I have to do to fix this will be in the Sharp side of things as essentially simpl+ is just iterating through the bulb list.

When I make updates to the underlying modules or simplsharp libraries, I typically do a recompile all in the demo program which recompiles all the underlying stuff using whatever has changed. That being said when doing development work and making changes to only the simplsharp library it saves a lot of time to simply stop the running simpl windows program, and sideload just the updated dll and issues a progreset command in console which the program then uses the new library without having to recompile all the other SIMPL windows and simpl+ stuff.

I’v been doing SIMPL and simpl+ since 2001 still relatively new to simplsharp and C#. I’ve been using these modules as a bit of a sandbox for me to experiment with some techniques. 


On Mar 1, 2018, at 12:11 PM, wint100 <notifications@github.com> wrote:

Although I now get the bulb6_name, calling the init or get function of the Bulb module returns nothing. Get usually returns an error. Init on the Room gets the rooms scenes etc.. but init on the HueBulb module doesn't seem to do anything. I use the make string permanent on the Bulb6_name.

**Comment by mthyden** [comment]
think I fixed the issue, all my bulbs reported in consecutive order and was able to control them all independently. Just pushed the update to github, I recompiled all the demo program so it should all be included.

On Mar 1, 2018, at 2:53 PM, Monte Thyden <mthyden@mac.com> wrote:

hmm yeah I tested it last night which is where I noticed my bulb id10 was missing. for my test I only defined bulbs 1-4, perhaps the skipping so for you past 5 other issues are exposed given the list mis-alignment, I’ll have to dig in and get the to the original root cause. I’ll try defining all my remaining bulbs first and see if I see the same as what you are seeing.

To your other questions regarding the SIMPL/SIMPLSharp environment, it all depends on what needs to change which dictates what changes regarding the various interfaces. the simplsharp library compiles into a CLZ which is a wrapper for the underlying dll. Simpl+ is our older language extension platform for SIMPL which we now use as our gatekeeper to bring in simplsharp libraries, the SIMPL WIndows has UMCs which are just wrapped logic symbols and other embedded modules which can include other SIMPL modules or simpl+ stuff. I suspect but could be wrong that whatever I have to do to fix this will be in the Sharp side of things as essentially simpl+ is just iterating through the bulb list.

When I make updates to the underlying modules or simplsharp libraries, I typically do a recompile all in the demo program which recompiles all the underlying stuff using whatever has changed. That being said when doing development work and making changes to only the simplsharp library it saves a lot of time to simply stop the running simpl windows program, and sideload just the updated dll and issues a progreset command in console which the program then uses the new library without having to recompile all the other SIMPL windows and simpl+ stuff.

I’v been doing SIMPL and simpl+ since 2001 still relatively new to simplsharp and C#. I’ve been using these modules as a bit of a sandbox for me to experiment with some techniques. 


On Mar 1, 2018, at 12:11 PM, wint100 <notifications@github.com <mailto:notifications@github.com>> wrote:

Although I now get the bulb6_name, calling the init or get function of the Bulb module returns nothing. Get usually returns an error. Init on the Room gets the rooms scenes etc.. but init on the HueBulb module doesn't seem to do anything. I use the make string permanent on the Bulb6_name.

**Comment by mthyden** [comment]
just posted the fix

**Comment by wint100** [comment]
I cans ee the bulb list is now in order, I get bulb names 1-6 in order. Trying to get bulbs still returns an exception regarding the index though:

Exception is System.ArgumentOutOfRangeException:     00:00:35.641
Parameter name: index    00:00:35.641
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)    00:00:35.641
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()    00:00:35.641
   at System.Collections.Generic.List`1.get_Item(Int32 index)    00:00:35.641
   at HueLights.HueLight.GetBulb()    00:00:35.641
   at UserModule_HUEBULB_R2_2.UserModuleClass_HUEBULB_R2_2.GETINFO_OnPush_0(Object __EventInfo__)    00:00:35.641
   at Amib.Threading.Internal.WorkItem.o()    00:00:35.641
   at Amib.Threading.Internal.WorkItem.Execute()    00:00:35.641
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)    00:00:35.641
   at Amib.Threading.SmartThreadPool.p()    00:00:35.641

**Comment by mthyden** [comment]
so same exception for all bulbs? and to confirm you set the init prior to the get correct? Not sure as I confirmed my own system with all bulbs even the ones that were previously out of order. Unfortunately I’m not going to be able to further troubleshoot anytime soon. Preparing for my Crestron Masters presentation. 

On Mar 8, 2018, at 9:27 AM, wint100 <notifications@github.com> wrote:

I cans ee the bulb list is now in order, I get bulb names 1-6 in order. Trying to get bulbs still returns an exception regarding the index though:

Exception is System.ArgumentOutOfRangeException: 00:00:35.641
Parameter name: index 00:00:35.641
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) 00:00:35.641
at System.ThrowHelper.ThrowArgumentOutOfRangeException() 00:00:35.641
at System.Collections.Generic.List`1.get_Item(Int32 index) 00:00:35.641
at HueLights.HueLight.GetBulb() 00:00:35.641
at UserModule_HUEBULB_R2_2.UserModuleClass_HUEBULB_R2_2.GETINFO_OnPush_0(Object EventInfo) 00:00:35.641
at Amib.Threading.Internal.WorkItem.o() 00:00:35.641
at Amib.Threading.Internal.WorkItem.Execute() 00:00:35.641
at Amib.Threading.SmartThreadPool.e(WorkItem A_0) 00:00:35.641
at Amib.Threading.SmartThreadPool.p() 00:00:35.641

**Comment by wint100** [comment]
Yes the same exception, I call init and then get, yes. I did try and update the files in my own project as I'd made quite a few changes such as add BACnet objects to talk to the BMS system. I copied the all the files from the following except for the lpz, sig and smw files:

PhillipsHueSIMPLSharp-master\SIMPL\PhillipsHue Demo v2.2_compiled.zip

**Comment by mthyden** [comment]
in my update there was a new version of the simpl+ 2.2 for the bulb and the CLZ obviously changed. have you tried hard coding the name into the parameter field rather then using the string input, I don’t see how that would be the issue but its worth giving a shot regardless. In your program if you open the Bulb UMC to verify its using the 2.2 simpl+ that would be worth checking. Also issue a progreset on your program slot and watch it in console, it should report in console the status of each init for the rooms and bulbs etc.Get <bulbname> complete.. or the failure

The init process iterates through the bulb list to match the name to find out what bulb ID it should use going forward. then the get simply utilizes that bulb id. This would be a bit of a PITA but you could force a cleanup of the bridge and read your bulbs as this would force them into a new bulb id structure.

I had started an entirely new branch where I redo some of my base classes and hope to implement a polling routine to support sensors and keypads in the future but won’t be getting back into that until After Masters.

On Mar 8, 2018, at 9:36 AM, wint100 <notifications@github.com> wrote:

Yes the same exception, I call init and then get, yes. I did try and update the files in my own project as I'd made quite a few changes such as add BACnet objects to talk to the BMS system. I copied the all the files from the following except for the lpz, sig and smw files:

PhillipsHueSIMPLSharp-master\SIMPL\PhillipsHue Demo v2.2_compiled.zip

**Comment by mthyden** [comment]
I added a few new bulbs and ran into the issue I think your experiencing, going to try to troubleshoot this weekend, I'll let you know.

**Comment by wint100** [comment]
I did manage to get the bulb on/off to work but none of the status signals ever change (online, level, status etc..) so I’ve left it in room control only for now.

Regards,

Mark Wint
BEC Ltd

On 23 Mar 2018, at 18:57, Monte Thyden <notifications@github.com<mailto:notifications@github.com>> wrote:


I added a few new bulbs and ran into the issue I think your experiencing, going to try to troubleshoot this weekend, I'll let you know.

**Comment by mthyden** [comment]
yeah I haven’t tried the individual operations for my failed bulbs yet but suspect I’d run into the same thing. I’m sure its something small will resolve tomorrow

On Mar 23, 2018, at 12:44 PM, wint100 <notifications@github.com> wrote:

I did manage to get the bulb on/off to work but none of the status signals ever change (online, level, status etc..) so I’ve left it in room control only for now. 

Regards, 

Mark Wint 
BEC Ltd 

On 23 Mar 2018, at 18:57, Monte Thyden <notifications@github.com<mailto:notifications@github.com>> wrote: 


I added a few new bulbs and ran into the issue I think your experiencing, going to try to troubleshoot this weekend, I'll let you know.

**Comment by mthyden** [comment]
OK just posted update, only the CLZ changed but I recompiled the demo program as well. I had to clear my data structures when the init fired, the previous break in bulb data prevented the fix from implementing correctly. should be resolved now, apologies for the inconvenience.

On Mar 23, 2018, at 12:44 PM, wint100 <notifications@github.com> wrote:

I did manage to get the bulb on/off to work but none of the status signals ever change (online, level, status etc..) so I’ve left it in room control only for now. 

Regards, 

Mark Wint 
BEC Ltd 

On 23 Mar 2018, at 18:57, Monte Thyden <notifications@github.com<mailto:notifications@github.com>> wrote: 


I added a few new bulbs and ran into the issue I think your experiencing, going to try to troubleshoot this weekend, I'll let you know.

**Comment by ptrout** [comment]
Hi
Playing with the demo for few lights in my office.
Everything functionally works fine from Crestron to Hue, but having trouble with level feedback.
I can do on/off, analog level in, even scene triggers.  But if I trigger a scene from Crestron or native Hue app, the analog values do not reflect back for Hue and Saturation, though brightness level does .
I seem to to be getting room data error.

hue_busy_alt  1  00:02:00.703
hue_rms_busy  1  00:02:00.703
hue_is_busy  1  00:02:00.703
rm1_get  1  00:02:00.703
::room_bri_out:S-10.1.5.4.1.000001F8  0.388%  00:02:00.734
::room_bri_out_scaled:S-10.1.5.4.1.00000207  100.000%  00:02:00.734
::room_bri_out_scaled_allow:S-10.1.5.4.1.00000208  100.000%  00:02:00.734
rm1_bri_out  100.000%  00:02:00.734
::room_hue_out:S-10.1.5.4.1.000001F9  0.000%  00:02:00.734
::room_hue_out_scaled_allow:S-10.1.5.4.1.0000020A  0.000%  00:02:00.734
rm1_hue_out  0.000%  00:02:00.734
::room_sat_out:S-10.1.5.4.1.000001FA  0.000%  00:02:00.734
::room_sat_out_scaled:S-10.1.5.4.1.0000020D  0.000%  00:02:00.734
::room_sat_out_scaled_allow:S-10.1.5.4.1.0000020E  0.000%  00:02:00.734
rm1_sat_out  0.000%  00:02:00.734
rm1_get  0  00:02:00.906
Error getting Room data:     00:02:03.906
rm2_get  1  00:02:03.906
::room_bri_out:S-10.1.5.5.1.00000215  0.000%  00:02:03.906
::room_hue_out:S-10.1.5.5.1.00000216  0.000%  00:02:03.906
::room_sat_out:S-10.1.5.5.1.00000217  0.000%  00:02:03.906
::room_bri_out_scaled:S-10.1.5.5.1.00000224  0.000%  00:02:03.906
::room_sat_out_scaled:S-10.1.5.5.1.0000022A  0.000%  00:02:03.906
rm2_get  0  00:02:04.093
Error getting Room data:     00:02:07.109
rm3_get  1  00:02:07.109
::room_bri_out:S-10.1.5.6.1.00000232  0.000%  00:02:07.109
::room_bri_out_scaled:S-10.1.5.6.1.00000241  0.000%  00:02:07.109
::room_hue_out:S-10.1.5.6.1.00000233  0.000%  00:02:07.125
::room_sat_out:S-10.1.5.6.1.00000234  0.000%  00:02:07.125
::room_sat_out_scaled:S-10.1.5.6.1.00000247  0.000%  00:02:07.125
rm3_get  0  00:02:07.296

Thank you for any thought if related to above.   And I also do can not control individual bulb parameters.  Though it discovers and retrieves name and type correctly.

**Comment by mthyden** [comment]
I won’t be able to look into this until after 4/13 due to the Crestron Masters summit.


On Apr 2, 2018, at 12:06 PM, ptrout <notifications@github.com> wrote:

Hi
Playing with the demo for few lights in my office.
Everything functionally works fine from Crestron to Hue, but having trouble with level feedback.
I can do on/off, analog level in, even scene triggers. But if I trigger a scene from Crestron or native Hue app, the analog values do not reflect back for Hue and Saturation, though brightness level does .
I seem to to be getting room data error.

hue_busy_alt 1 00:02:00.703
hue_rms_busy 1 00:02:00.703
hue_is_busy 1 00:02:00.703
rm1_get 1 00:02:00.703
::room_bri_out:S-10.1.5.4.1.000001F8 0.388% 00:02:00.734
::room_bri_out_scaled:S-10.1.5.4.1.00000207 100.000% 00:02:00.734
::room_bri_out_scaled_allow:S-10.1.5.4.1.00000208 100.000% 00:02:00.734
rm1_bri_out 100.000% 00:02:00.734
::room_hue_out:S-10.1.5.4.1.000001F9 0.000% 00:02:00.734
::room_hue_out_scaled_allow:S-10.1.5.4.1.0000020A 0.000% 00:02:00.734
rm1_hue_out 0.000% 00:02:00.734
::room_sat_out:S-10.1.5.4.1.000001FA 0.000% 00:02:00.734
::room_sat_out_scaled:S-10.1.5.4.1.0000020D 0.000% 00:02:00.734
::room_sat_out_scaled_allow:S-10.1.5.4.1.0000020E 0.000% 00:02:00.734
rm1_sat_out 0.000% 00:02:00.734
rm1_get 0 00:02:00.906
Error getting Room data: 00:02:03.906
rm2_get 1 00:02:03.906
::room_bri_out:S-10.1.5.5.1.00000215 0.000% 00:02:03.906
::room_hue_out:S-10.1.5.5.1.00000216 0.000% 00:02:03.906
::room_sat_out:S-10.1.5.5.1.00000217 0.000% 00:02:03.906
::room_bri_out_scaled:S-10.1.5.5.1.00000224 0.000% 00:02:03.906
::room_sat_out_scaled:S-10.1.5.5.1.0000022A 0.000% 00:02:03.906
rm2_get 0 00:02:04.093
Error getting Room data: 00:02:07.109
rm3_get 1 00:02:07.109
::room_bri_out:S-10.1.5.6.1.00000232 0.000% 00:02:07.109
::room_bri_out_scaled:S-10.1.5.6.1.00000241 0.000% 00:02:07.109
::room_hue_out:S-10.1.5.6.1.00000233 0.000% 00:02:07.125
::room_sat_out:S-10.1.5.6.1.00000234 0.000% 00:02:07.125
::room_sat_out_scaled:S-10.1.5.6.1.00000247 0.000% 00:02:07.125
rm3_get 0 00:02:07.296

Thank you for any thought if related to above. And I also do can not control individual bulb parameters. Though it discovers and retrieves name and type correctly.

**Comment by mthyden** [comment]
finally got around to looking into this, The individual bulb modules do get the feedback data but the SIMPL wrapper needs to be slightly tweaked to pass it correctly back out so that's minor. Looks like I may have broken the room feedback at the sharp level looking into this now. I should have a fix for both out shortly.

**Comment by mthyden** [comment]
ok, got it squared away and tested. Hue/Sat feedback has been fixed for room module and bulb module, pick up in the latest commit.

**Comment by wint100** [comment]
I've updated but still don't get a feedback on bulbs for Hue or Sat on all bulbs. Bulb 1 DOES show hue_out and sat_out, but other bulbs don't. Bulb1 in my system is an iris lamp, the others are E27 bulbs.

Also the _is_color is always Low on colour bulbs and a new issue, when a bulb is switch ON, the bri_out is 65535 but when switched off the bri_out stays at 65535 even though is_off goes high when I switch the bulb to off.

**Comment by wint100** [comment]
If it helps, I seem to be getting a few of the following errors:

Exception is System.NullReferenceException: NullReferenceException    00:00:12.656
   at HueLights.HttpConnect.Request(String url, String cmd, RequestType reqtype)    00:00:12.656
   at HueLights.HueLight.GetBulb()    00:00:12.656
   at UserModule_HUEBULB_R2_2.UserModuleClass_HUEBULB_R2_2.MYONLINEHANDLER(Object __sender__, EventArgs ARGS)    00:00:12.656
   at HueLights.HueLight.TriggerBulbOnlineUpdate()    00:00:12.656
   at HueLights.HueLight.BulbInit()    00:00:12.656
   at UserModule_HUEBULB_R2_2.UserModuleClass_HUEBULB_R2_2.INIT_OnPush_1(Object __EventInfo__)    00:00:12.656
   at Amib.Threading.Internal.WorkItem.o()    00:00:12.656
   at Amib.Threading.Internal.WorkItem.Execute()    00:00:12.656
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)    00:00:12.656
   at Amib.Threading.SmartThreadPool.p()    00:00:12.656

**Comment by mthyden** [comment]
The output values remain when the light is off, this is the way it has always been as bridge response reports those values even if the “on” property is false. This could be manipulated either on the SIMPL side or sharp side to send 0s while in an off state.

 

By the E27 model are you referring to LCT014 or LCT007 I have several of both types, what my parser looks for is if the colormode property exists where ct or xy and that sets the is color flag, sounds like something is funky in the bridge data. If you send me the output of the debug clip GET lights I can take a look.

**Comment by wint100** [comment]
I think mine are the LCT016, the new rev 9.5W bulb. This isn’t a major problem so don’t spend your weekend time in this. I’m just reporting any issues I come across to make the module as bullet proof as possible. It’s a great module to have available for free, works great for my Hue to BACnet projects to integrate to Building Management Systems.

Regards,

Mark Wint
BEC Ltd

On 29 Apr 2018, at 13:57, Monte Thyden <notifications@github.com<mailto:notifications@github.com>> wrote:

The output values remain when the light is off, this is the way it has always been as bridge response reports those values even if the “on” property is false. This could be manipulated either on the SIMPL side or sharp side to send 0s while in an off state.



By the E27 model are you referring to LCT014 or LCT007 I have several of both types, what my parser looks for is if the colormode property exists where ct or xy and that sets the is color flag, sounds like something is funky in the bridge data. If you send me the output of the debug clip GET lights I can take a look.

**Comment by mthyden** [comment]
Totally appreciate the feedback so keep it coming! I shouldn’t respond to emails before my morning coffee or else I’m prickly 😊

 

If you can send me the bulb json return that includes the LCT016 that would help me narrow it down. I would like to think the LCT016 still supports the colormode property but who knows. I’ve had to make mods in the past to my parsing routines to accommodate the Ikea bulbs. 

 

I’ve been working on one of my branches of this project that overhauls some of the plumbing so that it can utilize a queuing system in order to allow for polling for their motion sensor. As it stands I can throw a lot of requests at the bridge and it’s been robust but suspect when motion sensing polling or general use bulb / group polling is in play things may get dicey.

**Comment by mthyden** [comment]
Just posted another update that I think finally resolves the individual bulb feedback issues, LCT016 bulbs are fine, I have two now in my system and they control without issue. I recompiled the demo program as I had to tweak the bulb 2.2 umc as well as some simplsharp in the CLZ
