### ISSUE TITLE
Not Shure what I'm doing wrong Scenes and bulbs wont populate.

### ISSUE THREAD

**Issue by Krkconsult** [mthyden/PhillipsHueSIMPLSharp#21]
![image](https://user-images.githubusercontent.com/33847393/66278603-a563a000-e878-11e9-8849-e075aeea369b.png)

![image](https://user-images.githubusercontent.com/33847393/66278607-b3b1bc00-e878-11e9-87e7-8d75a770f2ab.png)

![image](https://user-images.githubusercontent.com/33847393/66278623-dcd24c80-e878-11e9-98da-68c985111bdf.png)

Thanks.

Kris

**Comment by Krkconsult** [comment]
My short tern goal is to call scenes.

Kris

**Comment by mthyden** [comment]
Send me your bridge data and I’ll test offline. https://developers.meethue.com/develop/get-started-2/
I would need the JSON responses, for bulbs, groups, scenes

Thanks

**Comment by Krkconsult** [comment]
[krk hue data.zip](https://github.com/mthyden/PhillipsHueSIMPLSharp/files/3695256/krk.hue.data.zip)

**Comment by mthyden** [comment]
So my processing implementation is failing to pick up Night Lights and Julian test for some reason, not getting any errors or exceptions from what I can tell.  I haven’t evaluated your scene data as of yet as that is a larger effort but I suspect the two rooms is what is hanging stuff up. The room data in the JSON for both of those rooms don’t jump out at me as causing an issue, I’ll need to dig deeper into it. I’d be curious if you removed those two rooms if the others would come up.

**Comment by Krkconsult** [comment]
Last night I removed all “in used rooms” 
The rooms with no bulbs were added to hue by Apple home. 

Interesting thing now. Only room 4 will populate the scene list on the xpanel. And that’s only if I trigger rm4_init in tool box after the room is selected on the panel.  

The other rooms still do not display in the list or in tool box. 

However I can trigger the scenes for other rooms via the x panel list buttons. 

Kris





Kris K.

**Comment by Krkconsult** [comment]
Night lights and Julian test were “groups” created in the new hue app. 

Kris K.

**Comment by mthyden** [comment]
Space out your inits at program start to at least .5s or 1s. I ran a quick test on my home system and noticed one of my room modules didn’t show the scenes text but like you saw was able to still trigger the scene correctly. I went from .2s to .5s in between the individual room inits and it worked fine. My home system has more overall bulbs but fewer spaces then you so perhaps I need some additional stress testing. Previously empty rooms was a bug that was addressed so if that is causing issues again I’ll need to look into it.

So your saying when you removed the empty Apple created rooms the rest of the rooms came online? Can you send me your updated JSON data as I am quite curious about the night Lights and Julian test rooms. I’ve only really encountered issues when reconciling scenes with rooms but have never seen at the room adding stage a room not get scooped up. Based on your last comment it sounds like its up with the exception of the scene text not populating correctly

**Comment by Krkconsult** [comment]
I’ll try upping the delays tonight and send you an updated Json too. 

Kris K.

**Comment by mthyden** [comment]
I stripped out some of the extraneous rooms and retested against your data, there is a condition where the scenes aren’t reconciling properly, I’m looking at it now. Its not related to timing as far as I can see currently.

**Comment by Krkconsult** [comment]
Thanks


Kris K.

**Comment by mthyden** [comment]
Just posted an update to the repo. Apparently the new Zones feature caused an issue with my scenes implementation. Essentially if any lights were used in both a group scene and a zone it would conflict. This has been corrected, I would still put in a delay between when the processor module comes online and when it starts init’ing each room/group. I threw in 5 dummy rooms with no lights in my system and it parsed them all correctly so not sure what you were seeing with the Apple generated rooms.

**Comment by Krkconsult** [comment]
Thanks I’ll try it tonight. 

My friend in Crestron say you have a reputation as an amazing programmer. 

Thanks for all your help and attention so far. 

Kris K.

**Comment by Krkconsult** [comment]
Well

 

It seems to parsing rooms 

 

Still not parsing scenes

 



 

Kris

**Comment by mthyden** [comment]
If you manually trigger a room init at runtime do the scenes populate? If you want I can remote in to you system to take a look, hit me up mthyden@gmail.com <mailto:mthyden@gmail.com> if interested.

**Comment by mthyden** [comment]
unclear if you are still having an issue, I'm closing this for now. let me know if I can be of any assistance.
